<a href="https://colab.research.google.com/github/sosullivan7221/HHA-507-WK1/blob/main/HHA_507_WK1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Pandas

In [1]:
import pandas as pd

## Dataset 1

Description: All of the winning numbers for the Mega Millions Lottery since 2002

Columns: ['Draw Date', 'Winning Numbers', 'Mega Ball', 'Multiplier']

In [6]:
df1 = pd.read_csv('/content/data/Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv')

df1_f10 = df1.head(10)

df1_f10

    Draw Date Winning Numbers  Mega Ball  Multiplier
0  09/25/2020  20 36 37 48 67         16         2.0
1  09/29/2020  14 39 43 44 67         19         3.0
2  10/02/2020  09 38 47 49 68         25         2.0
3  10/06/2020  15 16 18 39 59         17         3.0
4  10/09/2020  05 11 25 27 64         13         2.0
5  10/13/2020  11 44 45 46 70         25         2.0
6  10/16/2020  27 32 50 52 57         12         5.0
7  10/20/2020  46 54 57 58 66         10         3.0
8  10/23/2020  18 34 44 60 69         22         2.0
9  10/27/2020  06 13 34 46 62          1         3.0

## Dataset 2

Description: Crime data from Los Angeles dating back to 2020

Columns: ['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON']

In [8]:
df2 = pd.read_csv('/content/data/Crime_Data_from_2020_to_Present.csv')

df2_f10 = df2.head(10)

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1',
       'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT',
       'LON'],
      dtype='object')